movietitle = [
    ("OPPENHEIMER", "💣🧪👨‍🔬", "bomb, experiment, scientist"),
    ("BARBIE", "👱‍♀️🎀💖", "blonde woman, ribbon, pink heart"),
    ("INCEPTION", "💭🌀🔄", "thought bubble, spiral, repeat symbol"),
    ("AVATAR", "🌿👽🌳", "leaf, alien, tree"),
    ("DUNE", "🏜️🪱🚀", "desert, worm, rocket"),
    ("TENET", "⏳🔄🕰️", "hourglass, repeat symbol, clock"),
    ("INTERSTELLAR", "🌌🚀🕳️", "milky way, rocket, black hole"),
    ("JOKER", "🃏😈🤡", "joker card, devil, clown"),
    ("PARASITE", "🦠🏠🍽️", "microbe, house, fork and knife"),
    ("CODA", "🎵👂🤟", "musical note, ear, I love you hand sign"),
    ("TITANIC", "🚢❄️💔", "ship, ice, broken heart"),
    ("THE MATRIX", "💊🕶️💻", "pill, sunglasses, computer"),
    ("STAR WARS", "🌠🤖🌌", "star, robot, galaxy"),
    ("JURASSIC PARK", "🦖🏝️🧬", "dinosaur, tropical island, DNA"),
    ("FROZEN", "❄️👸🎵", "snowflake, princess, musical note"),
    ("BLACK PANTHER", "🐾🏴🦸🏿", "paw prints, black flag, black superhero"),
    ("AVENGERS", "🦸‍♀️🦸‍♂️💥", "female superhero, male superhero, explosion"),
    ("THE GODFATHER", "🍕🤵🔫", "pizza, person in tuxedo, pistol"),
    ("PULP FICTION", "🍔🕶️💼", "hamburger, sunglasses, briefcase"),
    ("FORREST GUMP", "🏃‍♂️🍫🪶", "running man, chocolate, feather"),
    ("THE LION KING", "🦁👑🌅", "lion, crown, sunrise"),
    ("TOY STORY", "🤠🚀🧸", "cowboy, rocket, teddy bear"),
    ("FIGHT CLUB", "👊🧼🤐", "fist, soap, zipped mouth"),
    ("THE SHINING", "🪓🏨👭", "axe, hotel, twin girls"),
    ("JAWS", "🦈🏖️🚤", "shark, beach, speedboat"),
    ("BACK TO THE FUTURE", "⏰🚗💨", "clock, car, smoke"),
    ("GLADIATOR", "⚔️🏛️🦁", "crossed swords, temple, lion"),
    ("SCHINDLER'S LIST", "📜🏭🕯️", "scroll, factory, candle"),
    ("GOODFELLAS", "🍝🔫💰", "spaghetti, pistol, money bag"),
    ("THE TERMINATOR", "🤖🕶️🔫", "robot, sunglasses, gun"),
    ("THE LORD OF THE RINGS", "💍🧙‍♂️🗻", "ring, wizard, mountain"),
    ("THE SILENCE OF THE LAMBS", "🔇🐑👨‍⚕️", "muted speaker, lamb, doctor"),
    ("SAVING PRIVATE RYAN", "🪖🏖️🎖️", "helmet, beach, medal"),
    ("THE PIANIST", "🎹🎭🇵🇱", "piano, theater masks, Polish flag"),
    ("THE DARK KNIGHT", "🦇🃏🏙️", "bat, joker card, cityscape"),
    ("THE GREEN MILE", "👮‍♂️💚⚡", "policeman, green heart, lightning bolt"),
    ("APOCALYPSE NOW", "🚁🌴💥", "helicopter, palm tree, explosion"),
    ("ALIEN", "👽🚀😱", "alien, rocket, scared face"),
    ("BLADE RUNNER", "🔪🏃‍♂️🤖", "knife, running man, robot"),
    ("E.T.", "👽🚲🌙", "alien, bicycle, moon"),
    ("THE SHAWSHANK REDEMPTION", "🔨🏃‍♂️🆓", "hammer, running man, free sign"),
    ("GOOD WILL HUNTING", "🧠🧹🏫", "brain, broom, school"),
    ("TWELVE ANGRY MEN", "1️⃣2️⃣😠👨‍⚖️", "12, angry face, judge"),
    ("ONE FLEW OVER THE CUCKOO'S NEST", "🦅🐣🏥", "eagle, chick, hospital"),
    ("THE SOUND OF MUSIC", "🎶⛰️🌼", "musical notes, mountain, flower"),
    ("CASABLANCA", "🕌🎶💏", "mosque, musical notes, couple kissing"),
    ("THE WIZARD OF OZ", "🌪️🥿🦁", "tornado, slipper, lion"),
    ("GONE WITH THE WIND", "🌪️🎩💏", "tornado, top hat, couple kissing")
]
